# Generated by Django 5.1.3 on 2024-12-01 01:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('setor_de_origem', models.CharField(max_length=100)),
                ('esta_ativo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=510)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias', to='core.veiculo')),
            ],
        ),
    ]
