# Generated by Django 5.1.3 on 2024-12-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_veiculo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='esta_ativo',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=False),
        ),
    ]
